// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1c2av7ee68f5rBoynNcfsW4nHWjzT85U',
    appId: '1:897370462781:web:71f3744e2db49b70436854',
    messagingSenderId: '897370462781',
    projectId: 'social-media-app-84e6f',
    authDomain: 'social-media-app-84e6f.firebaseapp.com',
    storageBucket: 'social-media-app-84e6f.firebasestorage.app',
    measurementId: 'G-0VV9PCMHPW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpm36iJETz2krHO6R6gzw4LuOoi7daiGY',
    appId: '1:897370462781:android:d4071db9a5924edf436854',
    messagingSenderId: '897370462781',
    projectId: 'social-media-app-84e6f',
    storageBucket: 'social-media-app-84e6f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9kxLwwc28v4_yCGXzbr5Zgp9zvPKmxtk',
    appId: '1:897370462781:ios:2981cf555c22cda6436854',
    messagingSenderId: '897370462781',
    projectId: 'social-media-app-84e6f',
    storageBucket: 'social-media-app-84e6f.firebasestorage.app',
    iosBundleId: 'com.example.socialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9kxLwwc28v4_yCGXzbr5Zgp9zvPKmxtk',
    appId: '1:897370462781:ios:2981cf555c22cda6436854',
    messagingSenderId: '897370462781',
    projectId: 'social-media-app-84e6f',
    storageBucket: 'social-media-app-84e6f.firebasestorage.app',
    iosBundleId: 'com.example.socialApp',
  );
}
